2-object/app.js
3-format/app.js
4-nested/app.js

line 204의 countArrayByType과
line 242의 countObjectByType가 중복이 되는 것 같으면서도 조금씩 달라서
계속 합치고 싶긴 한데 애매한 거 같습니다.

JSON 3. 엄격한 규칙 검사하기

---

arrayParser.js

Array Parser [STEP4 : 여러가지 타입 분석] 를 진행하고 있습니다.

[STEP4] Feat: 올바르지 않은 문자열 체크기능 추가

---

arrayParser3.js

(Whale) 3. 무한으로 중첩된 배열구조 분석

---

README.md
arrayParser.js

재귀로 구현한 상태에서 기능을 추가하려하니, 블랙홀을 헤메는 기분이였습니다...

[STEP5] Object Type 지원기능 추가

---

src/parser.js
src/statistic.js
test/statisticTest.js

[woogie]통계 STEP8

---

parser.js

[리오] Array Parser - STEP1 : Refactoring

---

README.md
function/arrayParser.js
function/lexer.js
function/print.js
function/utility.js
main.js
test/lexer.test.js

1. 정상적으로 종료되지 않은 배열을 검사하는 기능을 추가하였습니다.
2. 정상적으로 종료되지 않은 객체를 검사하는 기능을 추가하였습니다.
3. 객체 중 콜론이 누락된 경우를 검사하는 기능을 추가하였습니다.
4. 엄격한 검사로직으로 공백을 확인하는 부분을 추가하였습니다.
5. STEP7 개발에 대한 내용을 README에 추가하였습니다.

[HYEON] STEP 7 : 오류 상황 탐지

---

README.md
parser.js

[리오] Array Parser - STEP2

---

parser.js

STEP4 진행 했습니다 
뭔가 CheckDataType 함수를 Class화로 Refactoring이 가능할 것 같은.. 막연한 느낌이 있는데 
솔직히 명확하게 저것이 Class화가 가능한지 아니면 그 외에 다른 기능이 Class로 
Refactoring이 가능한 지 명확하게 아직은 잘 모르겠습니다;;;
리뷰 봐주시면서 이 궁금증에 대해서도 답변 부탁 드립니다.

[리오] Array Parser - STEP4

---

README.md
checkDataType.js
error.js
parser.js
tokenizer.js

STEP 5 진행 했습니다 
errorcase에 대한 테스트자동화(?) 리뷰에 대한 점은 아직 공부하지 못해서 ㅎㅎㅎ;; 
차차 진행해 가면서 알아보도록 하겠습니다

[리오] Array Parser - STEP5

---

checkDataType.js
error.js
parser.js

[리오] Array Parser - STEP7

---

checkDataType.js
count.js
error.js
expect.js
parser.js
test/test_PrimitiveData.js
test/test_error.js
test/test_parser.js

STEP 8 PR 보냅니다 
parser.js 에 parsingObj 매서드에서 76, 77라인처럼 
console.log로 출력하는 이 방법이 그다지 좋아 보이지 않는 듯한 막연한 느낌이 들어서...
좋은 것인지 아닌지 하는 생각이 들었는데 크롱의 의견이 어떤지 듣고 싶습니다.

[리오] Array Parser - STEP8

---

arrayParser.js
tester.js

Step1 첫 PR입니다.
검토 부탁드립니다 ^^~
---
p.s. (다 쓰고보니 얘가 더 기네요)
테스트 코드와 각주가 길어지는 게 싫어서, 
애플리케이션(arrayParser.js)과 테스트 코드(tester.js)를 각각 별도 파일로 분리해봤습니다.
ES6의 import/export를 써보려고 했는데,
VS code에서 Node.js로 디버깅할 때 오류가 나서, Node에서 export와 require를 빌려와 마무리했습니다.

[Step1] Add arrayParser module

---

arrayParser.js
tester.js

Step2 첫 PR입니다.
검토 부탁드립니다 ^^~
주요 변경점
---
* 배열 속 배열을 처리하게 개선했습니다.
* 토큰(쉼표와 ] )을 처리할 때 겹치는 동작을 한 메서드로 묶었습니다.
* 독립성이 약하던 util 객체를 rules 객체에 병합했습니다. 
느낀 점
---
* this 처리: 본 함수에서 네임스페이스 객체의 메서드를 호출할 때 this를 지정해서 불렀더니, 리팩토링하면서 해당 객체 안에서 다른 메서드를 호출할 때 this를 쓰지 못해서 머리가 엉키는 경험을 했습니다.

[Step2] Improve arrayParser to handle array children

---

arrayParser.js
structure_of_module.md
tester.js

아래와 같이 개선하였습니다.
* 무한중첩 배열 구조에서도 동작
* 토큰/자료구조 타입 처리 별도 메서드로 분리
* 프로그램 설계 소개서 추가

[Step3 ] Improve arrayParser to handle further array depth

---

arrayparser.js

-. 객체를 사용하지 않고 일단 해보았습니다.
-. step1을 하면서 설계의 중요성을 깨달았습니다.
확인 후 피드백바랍니다!

[Torco] Lec4 - Step1

---

arrayparser.js

-. tokenizer class를 만들어 arrayParser 함수에서 분리하였습니다.
-. 데이터 방향: arrayParser함수 -> Tokenizer class -> tokenizer.method -> dataFormat 함수 -> 반환
확인 후 리뷰 부탁드립니다.

[Torco] Lec4 - Step2

---

jsonArrayParser.js

-주어진 문자열에 대해 문자열의 타입 확인, 배열 내 원소 추출, 추출한 원소를 분석하는 메소드를 각각 구현하였습니다.
-정규표현식은 사용하지 않았습니다.
감사합니다.

Lec4 Array Parser 커밋 로그 step1

---

arrayparser.js
lexer.js
programming_structure.md
stack.js
tokenizer.js

- module 화하여 step4를 진행해보았습니다.
1. class Stack은 push, pop, peek 메소드만 두어 다른 곳에서도 쓸 수 있는 구조로 바꾸어 재 사용성을 높였습니다.
2. tokenizer은 인자로 받은 문자열을 나누는 역할, lexer는 나눠진 문자열을 type과 value를 부여하는 역할, parser는 lexer 모듈의 반환값을 통해 데이터 구조를 구축하는 역할로 나눠 독립성을 키웠습니다.
​
궁금한 점?
1. lexeme class에서 getType, getValue 메소드의 모양이 비슷한 거 같은데 합치는 게 좋을까요?
2. tokenizer에서 문자열을 나누는 기준이 실제로는 어떻게 되는지?
3. type 지원 범위가 확장되면서 if 구문이 늘어 가독성이 저해되는 건 아닌지?

[Torco] Step4 - 여러 Type 지원

---

arrayparser.js
lexer.js
programming_structure.md
tokenizer.js

- tokenizer에 object 타입을 분류할 수 있는 조건을 추가하였습니다.
- lexer에 ' : ' 포함여부에 따라 key를 분류하였습니다.
확인 후 리뷰 바랍니다.

[Torce] Step5 - Object 타입 추가

---

scripts.js

- lexer 함수에서 정규표현식을 많이 쓴거 같은데 더 줄여야 하나요!?
- 만들긴 하였는데 하드코딩을 한거같은 느낌이라 많은 피드백 부탁드립니다..ㅠㅠ

Step1 PR입니다

---

jsonArrayParser.js

-mainBranch, sideBranch를  rootBranch, lowerBranch로 변경하였습니다.
-새로운 브랜치 추가시 key 값의 유무(객체 또는 배열)에 따라 브랜치의 형태를 다르게 구성하는 메소드를 정의하였습니다.
-문자열 해체시 발생하는 다양한 처리 유형을 별도의 메소드로 분리하였습니다.
-문자열의 오류를 검사하는 메소드를 유형별로 분리하였습니다.

Lec4 Array Parser 커밋 로그 step5

---

scripts.js

- 기본적으로 let을 많이 사용하여 코드를 작성하였는데요. 재할당이 필요없는 변수들의 선언을 'const'로 변경하였습니다.
- const, let을 공부하면서 이전 var를 사용했을때와 가장 큰 특징인 블록레벨스코프와 호이스팅이 발생할 때 선언 단계에서 초기화 단계로 실행되는 흐름을 다시 한 번 파악해보았습니다. 
살펴보신 후 피드백 부탁드리겠습니다. 감사합니다.

Lecture 4, Step2 - Array Parser

---

Lec4_json.js

**STEP2. 2중 중첩 배열 분석**
코드 리뷰 부탁드립니다😃

[숨] lec4 - step2

---

arrayparser.js
lexer.js
stack.js
test/expect.js
test/test-data-lexer.js
test/test-data-parser.js
test/test-data-tokenizer.js
test/test.js
test/test.lexer.js
test/test.parser.js
test/test.tokenizer.js
tokenizer.js

아주 오랜만에 PR을 날리네요ㅠㅠ
- jest.js 기반으로 테스트 코드를 구현해보았습니다.
- toEqual 메소드를 통해 데이터를 비교하고
- toBe 메소드는 결과를 알려주는 역할을 하였습니다.
- jest에서 test 관련코드는 test 디렉토리에서 관리하는 것을 보아, 그렇게 해보았습니다.
확인 후 피드백 부탁드립니다.

[Torce] Step7 - 테스트 코드 구현

---

programming_structure.md
scripts.js

1. 설계도를 마크다운으로 추가하였습니다.
2. root 배열은 가장 중요한 변수이고 이 배열에 대한 외부 접근 가능성을 불안정하다고 느껴 weakMap을 이용하여 private하게 선언하였습니다.
3. 기존의 root의 각 위치를 참조하는 child, parent, curr의 관계를 다시 한 번 리펙토링 하였습니다.
감사합니다.

Lecture 4, Step3 - Array Parser

---

Lec4_json.js
information.md

**STEP3. 무한 중첩된 배열구조**
코드 리뷰 부탁드립니다! 😆

[숨] lec4 - step3

---

dataType.js
scripts.js

1. 타입과 각 타입의 오류 체크를 작성한 dataType 모듈을 추가하였습니다.
2. 타입의 오류는 정규 표현식을 사용하여 판별하였습니다.
살펴보신 후 피드백 부탁드리겠습니다. 감사합니다.

Lecture 4, Step4 - Array Parser

---

Lec4_json.js

**STEP4. 여러가지 Type**
step4 코드 리뷰 부탁드립니다. 
지난 스텝에서 결과값을 배열 말고 객체로 반환하는 게 좋겠다고 하셨는데요. 전체 로직을 건들지 않고 수정하는 방법을 잘 모르겠어서 일단 배열로 뒀습니다. 😢  여전히 수정하는 게 필요하다고 생각하시면 힌트를.. 주시면... 감사하겠습니다앗..

[숨] lec4 - step4

---

dataType.js
programming_structure.md
scripts.js

- 상태에 따른 데이터를 입력하는 변수가 curr, parent, child로 세가지였습니다. 리펙토링 과정에서 child 변수가 필요하지 않다고 판단되어 제거하였습니다. 
살펴보신 후 피드백 부탁드리겠습니다. 감사합니다.

Lecture 4, Step5 - Array Parser

---

App.js
dataType.js
error.js
scripts.js

- 문자열 안에 '{', '[', ',' 등 특수문자를 포함시키기 위해 리펙토링이 있었습니다.
- 에러 체크는 스텝에서 주어진 것 외에 배열, 객체가 닫힌 상황과 문자열이 정상적으로 닫히지 않은 경우를 추가하였습니다.
살펴보신 후 피드백 부탁드리겠습니다.

Lecture 4, Step6 - Array Parser

---

Lec4_json.js

**STEP5. 객체 Type**
코드 리뷰 부탁드립니다.
어떻게하면 끔찍한 분기문을 줄일 수 있을까요? 😢

[숨] lec4 - step5

---

Lec4_json.js

**STEP6. 오류상황 탐지**
아래 오류 상황을 탐지하는 코드를 추가하였습니다.
- 배열, 객체 닫힘 여부 확인
- 객체 내 콜론 누락 확인
- 문자열 어퍼스트로피 갯수 확인
- 객체 키 값에 어퍼스트로피 여부 확인
코드 리뷰 부탁드립니다~

[숨] lec4 - step6

---

arrayParser.js

- 기존 코드에서 comma를 확인하는 함수는 checker 함수에서 분리하고, 타입을 체크할 수 있는 checker 객체로 만들었습니다. 
- 기존 코드에서 타입을 분석하는 함수를 추가했습니다. 
- 일반적인 타입 체크 방법으로 타입을 확인할 수 없어 정규식을 이용해서 타입체크를 했습니다. 
- 타입 체크 중 에러 상황에 대해 
- console.error로 에러를 표시하고, 해당 type을 unknownType으로 출력해서 계속 함수를 진행할지
- throw error를 통해 진행하던 함수를 멈출지 
- 두 상황을 고민하다, 에러가 발생했을 때는 멈추고 에러를 표시하는 것이 낫다는 생각에 두 번째 방법으로 수정했는데, 어떤 것이 에러 처리에 더 좋을지 고민이 됩니다.

Step4 과제 제출합니다. 

---

Parser.js
errorMessages.js
literals.js
parserTest.js
separators.js

Step6-1 array parser 구현

---

arrayParser.js

Allen - Step6-1 ArrayParser 구현

---

app.js
node.js

[Jin] step 6-1 arrayParser 만들기

---

ArrayParser.js
app.js

Sony
Step 6-1 미션 구현 완료했습니다.
피드백 부탁드립니다. :)

Step6-1: Sony

---

parsing6-1.js

실수로 커밋을 나눠 올리진 못했습니다 ㅠㅠ 리뷰부탁드립니다.

Koon / step 6-1 구현완료

---

arrayParser.js

이전 PR을 지우고 commit 새로 옮겨서 다시 PR합니다!

Step6-1 Nailer

---

arrayParser.js

step 6-1에 있는 조건들을 가정하고 구현했습니다.
리뷰 부탁드립니다!

Step6-1 mukeunzi

---

arrayParser.js
lexer.js
node.js
parser.js
token.js
tokenTypeChecker.js
tokenizer.js
typeChecker.js

깃헙 주소에 변경이 있었습니다.(sel-dev -> P-iknow)   
리뷰 부탁드려요.

Step6-1 완료

---

parser.js

왕민 Step6-1

---

ArrayParser.js

commit을 새로 작성하여 다시 pr날립니다.
리뷰부탁드려요.

Re step6 1

---

README.md
step6-1/arrayParser.js
step6-1/parseTree.js
step6-1/parserTest.js
step6-1/parserUtils.js
step6-1/stack.js

TUNA - Step6-1 : ArrayParser 만들기

---

README.md
array_parser.js
lexer.js
parser.js
simulator.js

Step6-1 Array Parser 구현 완료했습니다!

---

ArrayParser.js

[Step6-1] H 미션 제출합니다.

---

arrayparser.js
lexer.js
parser.js
token.js
tokenizer.js

Michelle step 6-1 Arrayparser 구현

---

ArrayParser.js

Step6-1 + 무한중첩 

---

arrayParser.js

Step6-1 snow 구현 완료하였습니다.

---

README.md
arrayParser.js
arrayParser2.js

- arrayParser1.js 확인부탁드립니다.
- token, lexer, parser 을 arrayParser class 로 구현했습니다.
- arrayParser2.js 는 step6-2 미션으로, 수정중에 있습니다. branch 수정해서 pullrequest 하겠습니다.

Step6-1 arrayParser1.js  확인 부탁드립니다.

---

ArrayParser.js
DesignArrayParser.md
Node.js
app.js
lexer.js
tokenizer.js

Step 6-2 미션 구현 완료했습니다.
피드백 부탁드립니다. :)

Sony: Step6-2 미션 구현

---

ArrayParser.js

1. 올바른 문자열 체크 에러구현 위치와 typeof token === string 으로 한번더 따진부분이 아쉬운데 ㅠㅠ 
tokenize안에 내부함수를 구현하지않아서 이렇게 된것같습니다. 
개인적으로는 굳이 typecheck 함수를 만들필요가 있을까... 싶어서 이렇게 구현하였습니다. 
2. null은 typeof null이 object로 나오는데 하드코딩을 하지않고 해결할 방법이없을까요? 
3. 문자열의 경우 ''가 붙어서 넘어가므로 ''를 떼어주었습니다. 이떄 처음과 마지막을 token[0] , token[token.length-1]로 표현하지 않고 처음과마지막이 quote인지 확인하는 방법이 있을까요?
감사합니다><

wook step 6-2 구현 

---

arrayparser.js
lexer.js
parser.js
token.js

Step 6-2 feat 
- 무한중첩 구조 동작 구현
-  number 이외에 string, boolean, null 타입도 지원하도록 구현
- 올바른 문자열이 아닌 경우 에러처리 
리뷰 부탁드립니다~ 👩‍💻

Michelle Step6-2 Arrayparser

---

ArrayParser6-2.js
lexer6-2.js
tokenError6-2.js
tokenizer6-2.js
디자인.md

Newstep6 2 circus

---

ArrayParser.js

[Step6-2] H 미션 제출합니다.

---

analyst.js
app.js
arrayParser.js
errorChecker.js
lexer.js
node.js
stack.js
test/analyst.spec.js
tokenizer.js

[Allen] Step6-3 리뷰 부탁드립니다 :)

---

parser.js

추가미션은 진행하지 않고 object 타입 지원하도록 구현했습니다.
parser method 가 가독성이 떨어져서 리팩토링했는데 빠져나올수 없는 늪에 빠진느낌입니다...
확장성의 중요성을 느낀 미션이였습니다.

왕민 step6-3 리뷰 부탁드립니다.

---

arrayParser.js

CHANNY step6-3 제출합니다

---

step6-2/arrayparser.js
step6-2/parserutils.js
step6-2/parsetree.js
step6-2/stack.js
step6-2/test.js
step6-2/testutils.js

- arrayparser.js : tokenizer, lexer, parser 메서드 기능 및 최종 json 데이터 반환
- parserutils.js : parser 구현에 필요한 유틸성 메서드 구현
- parsetree.js : json데이터 형태로 만들어주는 클래스
- stack.js : tokenizer와 parser 구현에 필요한 stack ADT
- test.js : 유닛테스트 및 parser test 케이스 검증
- testutils.js : test에 필요한 유틸성 메서드 구현
- tokenizer 메서드 구현 시 reduce에서 splice하지 않고 세부 function으로 쪼개서 구현
- if 사용 시 중괄호를 사용해 컨벤션 지키도록 함
- 중복 및 필요 없는 타입 분류 제거 (decimal point, sign, whitespace)
- 유닛 테스트를 통해 검증 가능하도록 테스트 케이스 구현

TUNA Step6-2 : 무한중첩, 다양한 데이터 타입 비교

---

arrayparser.js
lexer.js
parser.js
token.js
tokenizer.js

추가 미션 제외하고 객체 분석하는 기능까지만 추가했습니다.
코드를 짜면서 고민했던 부분은..  Tokenizer, Lexer, Parser를 각각의 클래스로 분리했지만
그 후에 기능이 추가되면서 클래스 내부에 함수가 많아졌습니다.
클래스 내부에서 A 함수가 참 이어야 B 함수가 실행되는 등 함수간의 의존성이 높아지는 것을 느껴서, 이럴 때 어떻게 방어적으로 코딩 해야 하는지 잘 모르겠습니다. (대부분의 함수마다 에러 처리를 넣어야 하는지..)
개선 사항 말씀해주시면 수정해보겠습니다. 👩‍💻

Michelle Step 6-3 Arrayparser 구현
